// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: tokenmgmt/tokenmgmt.proto

package go_tokenmgmt_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token_Create_I struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Token_Create_I) Reset() {
	*x = Token_Create_I{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Create_I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Create_I) ProtoMessage() {}

func (x *Token_Create_I) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Create_I.ProtoReflect.Descriptor instead.
func (*Token_Create_I) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{0}
}

func (x *Token_Create_I) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Token_Drop_I struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Token_Drop_I) Reset() {
	*x = Token_Drop_I{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Drop_I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Drop_I) ProtoMessage() {}

func (x *Token_Drop_I) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Drop_I.ProtoReflect.Descriptor instead.
func (*Token_Drop_I) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{1}
}

func (x *Token_Drop_I) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Token_Write_I struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low  uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid  uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
}

func (x *Token_Write_I) Reset() {
	*x = Token_Write_I{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Write_I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Write_I) ProtoMessage() {}

func (x *Token_Write_I) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Write_I.ProtoReflect.Descriptor instead.
func (*Token_Write_I) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{2}
}

func (x *Token_Write_I) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token_Write_I) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token_Write_I) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Token_Write_I) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *Token_Write_I) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

type Token_Read_I struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Token_Read_I) Reset() {
	*x = Token_Read_I{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Read_I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Read_I) ProtoMessage() {}

func (x *Token_Read_I) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Read_I.ProtoReflect.Descriptor instead.
func (*Token_Read_I) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{3}
}

func (x *Token_Read_I) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Token_Create_O struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Token_Create_O) Reset() {
	*x = Token_Create_O{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Create_O) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Create_O) ProtoMessage() {}

func (x *Token_Create_O) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Create_O.ProtoReflect.Descriptor instead.
func (*Token_Create_O) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{4}
}

func (x *Token_Create_O) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Token_Drop_O struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Token_Drop_O) Reset() {
	*x = Token_Drop_O{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Drop_O) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Drop_O) ProtoMessage() {}

func (x *Token_Drop_O) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Drop_O.ProtoReflect.Descriptor instead.
func (*Token_Drop_O) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{5}
}

type Token_Write_O struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Partial_Value uint64 `protobuf:"varint,2,opt,name=partial_Value,json=partialValue,proto3" json:"partial_Value,omitempty"`
}

func (x *Token_Write_O) Reset() {
	*x = Token_Write_O{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Write_O) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Write_O) ProtoMessage() {}

func (x *Token_Write_O) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Write_O.ProtoReflect.Descriptor instead.
func (*Token_Write_O) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{6}
}

func (x *Token_Write_O) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Token_Write_O) GetPartial_Value() uint64 {
	if x != nil {
		return x.Partial_Value
	}
	return 0
}

type Token_Read_O struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Final_Value uint64 `protobuf:"varint,1,opt,name=final_Value,json=finalValue,proto3" json:"final_Value,omitempty"`
}

func (x *Token_Read_O) Reset() {
	*x = Token_Read_O{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Read_O) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Read_O) ProtoMessage() {}

func (x *Token_Read_O) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Read_O.ProtoReflect.Descriptor instead.
func (*Token_Read_O) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{7}
}

func (x *Token_Read_O) GetFinal_Value() uint64 {
	if x != nil {
		return x.Final_Value
	}
	return 0
}

type Comm_I struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Comm_I) Reset() {
	*x = Comm_I{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comm_I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comm_I) ProtoMessage() {}

func (x *Comm_I) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comm_I.ProtoReflect.Descriptor instead.
func (*Comm_I) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{8}
}

type Comm_O struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comm_Info string `protobuf:"bytes,1,opt,name=Comm_Info,json=CommInfo,proto3" json:"Comm_Info,omitempty"`
}

func (x *Comm_O) Reset() {
	*x = Comm_O{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comm_O) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comm_O) ProtoMessage() {}

func (x *Comm_O) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmgmt_tokenmgmt_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comm_O.ProtoReflect.Descriptor instead.
func (*Comm_O) Descriptor() ([]byte, []int) {
	return file_tokenmgmt_tokenmgmt_proto_rawDescGZIP(), []int{9}
}

func (x *Comm_O) GetComm_Info() string {
	if x != nil {
		return x.Comm_Info
	}
	return ""
}

var File_tokenmgmt_tokenmgmt_proto protoreflect.FileDescriptor

var file_tokenmgmt_tokenmgmt_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x44, 0x72, 0x6f, 0x70, 0x5f, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6b, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x22, 0x1e, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x52,
	0x65, 0x61, 0x64, 0x5f, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x0e, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x44, 0x72, 0x6f, 0x70, 0x5f, 0x4f, 0x22,
	0x4c, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x4f,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x61, 0x6c, 0x5f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a,
	0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x5f, 0x4f, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x08,
	0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x5f, 0x49, 0x22, 0x25, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d,
	0x5f, 0x4f, 0x12, 0x1b, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x32,
	0xc7, 0x02, 0x0a, 0x0f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x1a, 0x19, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x4f, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x04, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x17, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x44, 0x72, 0x6f, 0x70, 0x5f, 0x49, 0x1a, 0x17, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67,
	0x6d, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x44, 0x72, 0x6f, 0x70, 0x5f, 0x4f, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x5f, 0x49, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74,
	0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x4f, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x17, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x5f,
	0x49, 0x1a, 0x17, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x5f, 0x4f, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x11,
	0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x11, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x5f, 0x49, 0x1a, 0x11, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x5f, 0x4f, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tokenmgmt_tokenmgmt_proto_rawDescOnce sync.Once
	file_tokenmgmt_tokenmgmt_proto_rawDescData = file_tokenmgmt_tokenmgmt_proto_rawDesc
)

func file_tokenmgmt_tokenmgmt_proto_rawDescGZIP() []byte {
	file_tokenmgmt_tokenmgmt_proto_rawDescOnce.Do(func() {
		file_tokenmgmt_tokenmgmt_proto_rawDescData = protoimpl.X.CompressGZIP(file_tokenmgmt_tokenmgmt_proto_rawDescData)
	})
	return file_tokenmgmt_tokenmgmt_proto_rawDescData
}

var file_tokenmgmt_tokenmgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tokenmgmt_tokenmgmt_proto_goTypes = []interface{}{
	(*Token_Create_I)(nil), // 0: tokenmgmt.Token_Create_I
	(*Token_Drop_I)(nil),   // 1: tokenmgmt.Token_Drop_I
	(*Token_Write_I)(nil),  // 2: tokenmgmt.Token_Write_I
	(*Token_Read_I)(nil),   // 3: tokenmgmt.Token_Read_I
	(*Token_Create_O)(nil), // 4: tokenmgmt.Token_Create_O
	(*Token_Drop_O)(nil),   // 5: tokenmgmt.Token_Drop_O
	(*Token_Write_O)(nil),  // 6: tokenmgmt.Token_Write_O
	(*Token_Read_O)(nil),   // 7: tokenmgmt.Token_Read_O
	(*Comm_I)(nil),         // 8: tokenmgmt.Comm_I
	(*Comm_O)(nil),         // 9: tokenmgmt.Comm_O
}
var file_tokenmgmt_tokenmgmt_proto_depIdxs = []int32{
	0, // 0: tokenmgmt.TokenManagement.Create:input_type -> tokenmgmt.Token_Create_I
	1, // 1: tokenmgmt.TokenManagement.Drop:input_type -> tokenmgmt.Token_Drop_I
	2, // 2: tokenmgmt.TokenManagement.Write:input_type -> tokenmgmt.Token_Write_I
	3, // 3: tokenmgmt.TokenManagement.Read:input_type -> tokenmgmt.Token_Read_I
	8, // 4: tokenmgmt.TokenManagement.CommunicationInfo:input_type -> tokenmgmt.Comm_I
	4, // 5: tokenmgmt.TokenManagement.Create:output_type -> tokenmgmt.Token_Create_O
	5, // 6: tokenmgmt.TokenManagement.Drop:output_type -> tokenmgmt.Token_Drop_O
	6, // 7: tokenmgmt.TokenManagement.Write:output_type -> tokenmgmt.Token_Write_O
	7, // 8: tokenmgmt.TokenManagement.Read:output_type -> tokenmgmt.Token_Read_O
	9, // 9: tokenmgmt.TokenManagement.CommunicationInfo:output_type -> tokenmgmt.Comm_O
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokenmgmt_tokenmgmt_proto_init() }
func file_tokenmgmt_tokenmgmt_proto_init() {
	if File_tokenmgmt_tokenmgmt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tokenmgmt_tokenmgmt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Create_I); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Drop_I); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Write_I); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Read_I); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Create_O); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Drop_O); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Write_O); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Read_O); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comm_I); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenmgmt_tokenmgmt_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comm_O); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tokenmgmt_tokenmgmt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenmgmt_tokenmgmt_proto_goTypes,
		DependencyIndexes: file_tokenmgmt_tokenmgmt_proto_depIdxs,
		MessageInfos:      file_tokenmgmt_tokenmgmt_proto_msgTypes,
	}.Build()
	File_tokenmgmt_tokenmgmt_proto = out.File
	file_tokenmgmt_tokenmgmt_proto_rawDesc = nil
	file_tokenmgmt_tokenmgmt_proto_goTypes = nil
	file_tokenmgmt_tokenmgmt_proto_depIdxs = nil
}
